### ISSUE TITLE
Error after building dll

### ISSUE THREAD

**Issue by Zumbalamambo** [lagadic/visp_unity#19] opened 2020-02-15 00:51 UTC
I have built the dll file exactly as mentioned in the wiki.

However when I'm trying to run the code, I'm getting `Plugins: Failed to load 'Assets/ViSPUnity.dll' because one or more of its dependencies could not be loaded.` error.

Do you have any ideas as in how we could fix it?

**Comment by USER1999-svg** [comment] 2020-03-26 18:52
@Zumbalamambo did you find solution to this problem , i have the same problem ..

**Comment by fspindle** [comment] 2020-03-28 10:50
See my post in #14.
I suspect that your `PATH` environment variable doesn't contain the location of the 3rd parties that are used in ViSP build

**Comment by USER1999-svg** [comment] 2020-03-28 22:38
thank's a lot .
I solve it by adding .dll needed like Coin4.dll missed .
@fspindle Itry now to use this exemple to do a tracking of object without apriltag using generic tutorial ; my code. cpp is tutorial-mb-generic-tracker-live.cpp with Wrl model .. Im bigger with C# ,, is there any tutorial or C#source code  can help me to use this exemple with unity ?

**Comment by fspindle** [comment] 2020-04-05 14:12
There is no example with vrml in Unity.
From the changes introduced in PR #21 that will be merged soon in the master branch you should be able to adapt the code to what is inside tutorial-mb-generic-tracker-live.cpp

**Comment by USER1999-svg** [comment] 2020-04-09 11:24
@fspindle  the problem is that I can't integrate the intialisation of object detection with file " .init" and load Cao model in game screen ..

**Comment by fspindle** [comment] 2020-04-09 12:59
There is the `Script_mbt.cs` that shows how to load the cao file for the tracker.
It creates the cao file calling `Visp_MbGenericTracker_CreateCaoFile()`. In your case you can start copying your specific cao file in `unityProject` folder. Then just modify `Visp_MbGenericTracker_Init()` replacing `cube.cao` with your file name. 

Concerning the `.init` file you should get inspiration from [vpMbTracker::initClick()](https://visp-doc.inria.fr/doxygen/visp-daily/classvpMbTracker.html#a880c4d5929957572734c25b901635333)
- create a new C++ function that opens the `.init` file to get the 3D coordinates of at least the 4 points that should be present and return the "number of points" in Unity
- in Unity create a function that allows "number of points" user click so that the user can click in the image and get the corresponding 2D coordinates af the points
- call a C++ function passing the 2D coordinates of the points that computes the pose using 2D (from user click) - 3D (from `.init` file) point correspondances. This functions returns the pose.

You should than also modify `Visp_MbGenericTracker_Process()` to pass the pose for the initialization.

**Comment by USER1999-svg** [comment] 2020-04-09 13:37
--i'm begginer with unity and C# programming , how i can create a function that allows "number of points" user click so that the user can click in the image and get the corresponding 2D coordinates af the points? 
-- i don(t understand what you mean by call a C++ function passing the 2D coordinates of the points that computes the pose using 2D (from user click) - 3D (from .init file) point correspondances. This functions returns the pose.

**Closed as completed** 2022-12-30 12:49 UTC
